replicaCount: 1

image:
  repository: nginx
  tag: "1.27.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

htmlContent: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
        <p>This is served by eayar.</p>
    </body>
    </html>
